backend:
  name: github
  repo: belovedchurch/cms-with-hugo
  use_graphql: true

media_folder: "assets/images/uploads"
collections:
  - name: posts
    label: post
    folder: "content/posts"
    create: true
    slug: '{{slug}}'
    format: "toml-frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", picker_utc: true }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Body", name: "body", widget: "markdown" }
